FROM node:20-alpine

WORKDIR /app

# Alpine için Prisma'nın ihtiyaç duyduğu libc6-compat ve openssl'i ekliyoruz
RUN apk add --no-cache openssl python3 make g++ libc6-compat

COPY package*.json ./
COPY prisma ./prisma/

# Bağımlılıkları yükle
RUN npm install

# Prisma client üret
RUN npx prisma generate

COPY . .

EXPOSE 5000

# Geliştirme aşamasında local veritabanıyla çalışırken şemanın hep güncel kalması için:
CMD ["sh", "-c", "npx prisma generate && npm run dev -- -p 5000"]