services:
  app:
    image: ghcr.io/enesbasar611/telefon-takip-v2:latest
    container_name: telefon-takip
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.telefon-takip.rule=Host(`basarteknik.tech`)"
      - "traefik.http.routers.telefon-takip.entrypoints=websecure"
      - "traefik.http.routers.telefon-takip.tls=true"

      # --- WebSocket & Sticky Sessions ---
      - "traefik.http.services.telefon-takip.loadbalancer.server.port=5000"
      - "traefik.http.services.telefon-takip.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.telefon-takip.loadbalancer.sticky.cookie.name=basar_teknik_socket"
      - "traefik.http.services.telefon-takip.loadbalancer.sticky.cookie.httpOnly=true"

      # HTTPS Header Yönlendirmesi
      - "traefik.http.routers.telefon-takip.middlewares=sslheader"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"

    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://basarteknik.tech
      - AUTH_TRUST_HOST=true # NextAuth v4 için Traefik güvenliği

    volumes:
      - whatsapp-auth:/app/.whatsapp-auth

volumes:
  whatsapp-auth:
