FROM node:20-alpine

WORKDIR /app

# Gerekli sistem paketleri (Alpine için)
RUN apk add --no-cache openssl python3 make g++

# Sadece package dosyalarını kopyalayarak bağımlılık katmanını önbelleğe alıyoruz
COPY package*.json ./
COPY prisma ./prisma/

# Bağımlılıkları yükle
RUN npm install

# Prisma client üret
RUN npx prisma generate

# Uygulama kodlarını kopyala
COPY . .

# Port ayarı (local'de 5000)
EXPOSE 5000

# Next.js development server başlat
CMD ["npm", "run", "dev", "--", "-p", "5000"]
