ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "salaryPaymentDay" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "employmentEndedAt" TIMESTAMP(3);

ALTER TABLE "Notification"
ADD COLUMN IF NOT EXISTS "metadata" JSONB;
